# Generated by Django 5.2.7 on 2025-10-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_author_remove_comment_writer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='guestname',
            field=models.CharField(),
        ),
    ]
